### PR TITLE
Add install target

### LINKED ISSUE #162: CMake install target
This is just more convenient.

Things we may want to install:
- Kepka binary itself
- kepka.desktop
- tg.protocol
- Telegram/Resources/art/icon*.png

### PR DESCRIPTION
**Pull request by foxcpp**
Honestly, did only brief testing and I have no idea how it would work on Windows.
It installs exactly what my AUR package installs (see #162).

Closes #162.

### CODE REVIEW

**Comment by xvitaly** [comment]
Add `lib/xdg/kepka.appdata.xml` file too. It must be installed to `share/metainfo/`.

**Comment by crackedmind** [comment]
:white_check_mark: [Build kepka 1.0.132-pxrhavyo completed](https://ci.appveyor.com/project/procxx/tdesktop/build/1.0.132-pxrhavyo) (commit https://github.com/procxx/kepka/commit/c27d0e05fe by @foxcpp)

**Comment by xvitaly** [comment]
Also you must add `${CMAKE_INSTALL_DATAROOTDIR}` to each row.

**Comment by crackedmind** [comment]
:white_check_mark: [Build kepka 1.0.133-bavlsdvb completed](https://ci.appveyor.com/project/procxx/tdesktop/build/1.0.133-bavlsdvb) (commit https://github.com/procxx/kepka/commit/c68b0dd774 by @foxcpp)

**Review by xvitaly — APPROVED** [review]
LGTM. Thanks for your contribution.

**Pull request merged**
