### PR TITLE
RPM package for Fedora

### LINKED ISSUE #32: RPM package for Fedora
- [x] Create basic RPM SPEC for Fedora.
- [ ] Rename temporary package name to final.
- [ ] Create CI task to build package on Koji after each commit.
- [ ] Remove all third-party libraries from repository.
- [ ] Use packaged dependencies: minizip, libtgvoip, etc.

### PR DESCRIPTION
**Pull request by xvitaly**
RPM package for Fedora. Closes #32.

### CODE REVIEW

**Comment by crackedmind** [comment]
:white_check_mark: [Build kepka 1.0.29-eghgtryi completed](https://ci.appveyor.com/project/procxx/tdesktop/build/1.0.29-eghgtryi) (commit https://github.com/procxx/kepka/commit/44f13d3075 by @xvitaly)

**Comment by berkus** [comment]
Squash and rename commit pls?

**Review by berkus — CHANGES_REQUESTED** [review]
Squash and rename commit pls?

**Comment by xvitaly** [comment]
> Squash and rename commit pls?

Done.

**Review by berkus — APPROVED** [review]

**Pull request merged**
