### PR TITLE
Fix warnings

### PR DESCRIPTION
**Pull request by crackedmind**

### CODE REVIEW

**Comment by crackedmind** [comment]
:white_check_mark: [Build kepka 1.0.92-jemxemef completed](https://ci.appveyor.com/project/procxx/tdesktop/build/1.0.92-jemxemef) (commit https://github.com/procxx/kepka/commit/754e8c1810 by @crackedmind)

**Review by ForNeVeR — DISMISSED** [review]

**Comment by crackedmind** [comment]
:white_check_mark: [Build kepka 1.0.92-fuvlubwd completed](https://ci.appveyor.com/project/procxx/tdesktop/build/1.0.92-fuvlubwd) (commit https://github.com/procxx/kepka/commit/f7fd18cfcc by @crackedmind)

**Comment by crackedmind** [comment]
:white_check_mark: [Build kepka 1.0.92-mpijapin completed](https://ci.appveyor.com/project/procxx/tdesktop/build/1.0.92-mpijapin) (commit https://github.com/procxx/kepka/commit/25ea7eb9e9 by @leha-bot)

**Comment by crackedmind** [comment]
:white_check_mark: [Build kepka 1.0.92-xvqhvicp completed](https://ci.appveyor.com/project/procxx/tdesktop/build/1.0.92-xvqhvicp) (commit https://github.com/procxx/kepka/commit/c0f6d197d6 by @leha-bot)

**Comment by crackedmind** [comment]
:white_check_mark: [Build kepka 1.0.92-sumtdugb completed](https://ci.appveyor.com/project/procxx/tdesktop/build/1.0.92-sumtdugb) (commit https://github.com/procxx/kepka/commit/be65590676 by @leha-bot)

**Pull request merged**
