### PR TITLE
Fix warnings

### PR DESCRIPTION
**Pull request by Randl**
Reduce entropy a bit

### CODE REVIEW

**Comment by Randl** [comment]
A small part of it)

**Comment by crackedmind** [comment]
:white_check_mark: [Build kepka 1.0.130-phnrnyid completed](https://ci.appveyor.com/project/procxx/tdesktop/build/1.0.130-phnrnyid) (commit https://github.com/procxx/kepka/commit/f339722c43 by @Randl)

**Comment by crackedmind** [comment]
:white_check_mark: [Build kepka 1.0.131-bnkwbvbh completed](https://ci.appveyor.com/project/procxx/tdesktop/build/1.0.131-bnkwbvbh) (commit https://github.com/procxx/kepka/commit/08de267859 by @Randl)

**Comment by crackedmind** [comment]
:white_check_mark: [Build kepka 1.0.132-scxmxfwl completed](https://ci.appveyor.com/project/procxx/tdesktop/build/1.0.132-scxmxfwl) (commit https://github.com/procxx/kepka/commit/cf436ed543 by @Randl)

**Comment by crackedmind** [comment]
:white_check_mark: [Build kepka 1.0.132-kevpukri completed](https://ci.appveyor.com/project/procxx/tdesktop/build/1.0.132-kevpukri) (commit https://github.com/procxx/kepka/commit/0cae53fe83 by @Randl)

**Comment by crackedmind** [comment]
:white_check_mark: [Build kepka 1.0.134-icfthbvr completed](https://ci.appveyor.com/project/procxx/tdesktop/build/1.0.134-icfthbvr) (commit https://github.com/procxx/kepka/commit/db820ef7fe by @Randl)

**Pull request merged**
