### PR TITLE
Rtl fix

### LINKED ISSUE #103: Disable damned RTL and related Unicode chars by default
To avoid these phishing attacks: https://xakep.ru/2018/02/13/telegram-rlo/

### PR DESCRIPTION
**Pull request by Randl**
It should close #103

(edited by @leha-bot for GH Automation)

### CODE REVIEW

**Comment by ForNeVeR** [comment]
Maybe squash these?

**Comment by Randl** [comment]
https://www.openssl.org/docs/man1.1.0/crypto/ERR_remove_state.html

**Comment by crackedmind** [comment]
:white_check_mark: [Build kepka 1.0.130-ntavlaaq completed](https://ci.appveyor.com/project/procxx/tdesktop/build/1.0.130-ntavlaaq) (commit https://github.com/procxx/kepka/commit/687eec0a23 by @Randl)

**Comment by crackedmind** [comment]
:white_check_mark: [Build kepka 1.0.130-jwpelarq completed](https://ci.appveyor.com/project/procxx/tdesktop/build/1.0.130-jwpelarq) (commit https://github.com/procxx/kepka/commit/79f8a0725a by @Randl)

**Comment by crackedmind** [comment]
:white_check_mark: [Build kepka 1.0.132-gycbiupe completed](https://ci.appveyor.com/project/procxx/tdesktop/build/1.0.132-gycbiupe) (commit https://github.com/procxx/kepka/commit/36bf69ed27 by @Randl)

**Pull request merged**
