### PR TITLE
Appveyor Level Up

### LINKED ISSUE #57: Appveyor Level Up
- [x] build only `RelWithDebInfo` on Appveyor
- [x] pack it without PDB
- [x] pack PDBs into a separate archive
- [x] run `ctest` (`ctest .`, see on Travis)
- [x] publish `Release` to GitHub releases (see [this](https://github.com/matwey/fips3/blob/60c1bfd5d6cee9bced17fe5b19347c5be9cffa8e/.appveyor.yml#L32-L43) as an example)

### PR DESCRIPTION
**Pull request by ForNeVeR**
Closes #57.

### CODE REVIEW

**Comment by crackedmind** [comment]
:x: [Build kepka 1.0.83-eixciucn failed](https://ci.appveyor.com/project/procxx/tdesktop/build/1.0.83-eixciucn) (commit https://github.com/procxx/kepka/commit/23e8eedc7a by @ForNeVeR)

**Comment by crackedmind** [comment]
:x: [Build kepka 1.0.83-cxtysmak failed](https://ci.appveyor.com/project/procxx/tdesktop/build/1.0.83-cxtysmak) (commit https://github.com/procxx/kepka/commit/b9342c2bfc by @ForNeVeR)

**Comment by crackedmind** [comment]
:white_check_mark: [Build kepka 1.0.84-vrbvosqc completed](https://ci.appveyor.com/project/procxx/tdesktop/build/1.0.84-vrbvosqc) (commit https://github.com/procxx/kepka/commit/c37419bdc0 by @ForNeVeR)

**Comment by crackedmind** [comment]
:white_check_mark: [Build kepka 1.0.84-boacigin completed](https://ci.appveyor.com/project/procxx/tdesktop/build/1.0.84-boacigin) (commit https://github.com/procxx/kepka/commit/0cbbfd9f99 by @ForNeVeR)

**Comment by crackedmind** [comment]
:white_check_mark: [Build kepka 1.0.84-tfixcojb completed](https://ci.appveyor.com/project/procxx/tdesktop/build/1.0.84-tfixcojb) (commit https://github.com/procxx/kepka/commit/dccde16ea4 by @ForNeVeR)

**Comment by crackedmind** [comment]
:x: [Build kepka 1.0.84-eqysrtyg failed](https://ci.appveyor.com/project/procxx/tdesktop/build/1.0.84-eqysrtyg) (commit https://github.com/procxx/kepka/commit/4f2476d2e8 by @ForNeVeR)

**Comment by crackedmind** [comment]
:x: [Build kepka 1.0.84-ayoqwknf failed](https://ci.appveyor.com/project/procxx/tdesktop/build/1.0.84-ayoqwknf) (commit https://github.com/procxx/kepka/commit/e6e9c7edcb by @ForNeVeR)

**Comment by crackedmind** [comment]
:white_check_mark: [Build kepka 1.0.84-btrdroij completed](https://ci.appveyor.com/project/procxx/tdesktop/build/1.0.84-btrdroij) (commit https://github.com/procxx/kepka/commit/b3be9f4e1f by @ForNeVeR)

**Comment by crackedmind** [comment]
:white_check_mark: [Build kepka 1.0.84-xxkucdaw completed](https://ci.appveyor.com/project/procxx/tdesktop/build/1.0.84-xxkucdaw) (commit https://github.com/procxx/kepka/commit/6abff41f75 by @ForNeVeR)

**Comment by crackedmind** [comment]
:white_check_mark: [Build kepka 1.0.84-edtwryny completed](https://ci.appveyor.com/project/procxx/tdesktop/build/1.0.84-edtwryny) (commit https://github.com/procxx/kepka/commit/16edd62401 by @ForNeVeR)

**Comment by crackedmind** [comment]
:white_check_mark: [Build kepka 1.0.84-iikfluxp completed](https://ci.appveyor.com/project/procxx/tdesktop/build/1.0.84-iikfluxp) (commit https://github.com/procxx/kepka/commit/3463dd59e2 by @ForNeVeR)

**Comment by ForNeVeR** [comment]
It's ready, although I wasn't able to check if my deployment configuration works.

**Review by crackedmind — APPROVED** [review]

**Pull request merged**
