### PR TITLE
Fix non-utf8 text in commit 31ed5214f023f99a40d3e73938d95ac630c26d13

### PR DESCRIPTION
**Pull request by berkus**

### CODE REVIEW

**Review by zamazan4ik — DISMISSED** [review]

**Comment by berkus** [comment]
Problem with original commit is such: quotes are entered in cp1251 encoding.

bad-quotes

**Comment by berkus** [comment]
⚔️ blocked on `ci_travis` merge before we can run PR validation

**Comment by crackedmind** [comment]
:white_check_mark: [Build kepka 1.0.42-xrgnbiox completed](https://ci.appveyor.com/project/procxx/tdesktop/build/1.0.42-xrgnbiox) (commit https://github.com/procxx/kepka/commit/03687819b7 by @berkus)

**Review by zamazan4ik — APPROVED** [review]

**Comment by crackedmind** [comment]
:white_check_mark: [Build kepka 1.0.46-rxusgoro completed](https://ci.appveyor.com/project/procxx/tdesktop/build/1.0.46-rxusgoro) (commit https://github.com/procxx/kepka/commit/0891ed0e4f by @berkus)

**Comment by crackedmind** [comment]
@crackedmind бле надо отдельный акк завести, обозвать ботом

**Pull request merged**
