### PR TITLE
Use AL_DIRECT_CHANNELS_SOFT for audio playback.

### PR DESCRIPTION
**Pull request by foxcpp**
See https://github.com/telegramdesktop/tdesktop/issues/2580.

(cherry picked from commit e3b6e1325e0d8dff9c428f293d468c7c2a1c3329)

### CODE REVIEW

**Comment by Hexawolf** [comment]
uhh, sure, this will do the trick but `AL_DIRECT_CHANNELS_SOFT` was designed quite poorly. The intended use here is to avoid direct channels and play via virtual speakers. As I've also mentioned in comment for the original commit, it must be tested on real 5.1 system before I'd like to see it merged. According to my prediction, front-center and surround channels are going to be dropped.

**Comment by crackedmind** [comment]
:x: [Build kepka 1.0.220-rebbvgqi failed](https://ci.appveyor.com/project/procxx/tdesktop/builds/21443577) (commit https://github.com/procxx/kepka/commit/829e772162 by @john-preston)

**Comment by crackedmind** [comment]
:white_check_mark: [Build kepka 1.0.220-cpjbqojn completed](https://ci.appveyor.com/project/procxx/tdesktop/builds/21458810) (commit https://github.com/procxx/kepka/commit/829e772162 by @john-preston)

**Comment by foxcpp** [comment]
https://github.com/openalext/openalext/wiki/AL_SOFT_direct_channels
>    AL_DIRECT_CHANNELS_SOFT set to AL_TRUE indicates the audio channels are
>    not virtualized and play directly on the matching output channels if they
>    exist, otherwise they are dropped. Applies only when playing non-mono
>    buffers.

**Pull request merged**
