### PR TITLE
Convert build script to PowerShell

### LINKED ISSUE #205: AppVeyor doesn't show build failure properly

### PR DESCRIPTION
**Pull request by ForNeVeR**
Close #205.

For now, I plan to test if it actually will fail on build error. Please do not merge right now.

### CODE REVIEW

**Comment by crackedmind** [comment]
:white_check_mark: [Build kepka 1.0.186-cetklbnq completed](https://ci.appveyor.com/project/procxx/tdesktop/builds/19845286) (commit https://github.com/procxx/kepka/commit/ea9b4a137b by @ForNeVeR)

**Comment by crackedmind** [comment]
:x: [Build kepka 1.0.186-nwomqibu failed](https://ci.appveyor.com/project/procxx/tdesktop/builds/19845794) (commit https://github.com/procxx/kepka/commit/33a8eabdf0 by @ForNeVeR)

**Comment by ForNeVeR** [comment]
Ready.

**Comment by crackedmind** [comment]
:white_check_mark: [Build kepka 1.0.186-tcpraaec completed](https://ci.appveyor.com/project/procxx/tdesktop/builds/19845951) (commit https://github.com/procxx/kepka/commit/c6ae77e000 by @ForNeVeR)

**Review by Randl — APPROVED** [review]

**Review by crackedmind — APPROVED** [review]

**Pull request merged**
