### PR TITLE
Fix the executable name for Appveyor

### PR DESCRIPTION
**Pull request by ForNeVeR**

### CODE REVIEW

**Comment by crackedmind** [comment]
:white_check_mark: [Build kepka 1.0.152-xsarfppb completed](https://ci.appveyor.com/project/procxx/tdesktop/build/1.0.152-xsarfppb) (commit https://github.com/procxx/kepka/commit/8c0d9f35a9 by @ForNeVeR)

**Comment by crackedmind** [comment]
:white_check_mark: [Build kepka 1.0.156-iuqbjask completed](https://ci.appveyor.com/project/procxx/tdesktop/build/1.0.156-iuqbjask) (commit https://github.com/procxx/kepka/commit/d93e0ff282 by @ForNeVeR)

**Comment by crackedmind** [comment]
:x: [Build kepka 1.0.156-jkqlpgva failed](https://ci.appveyor.com/project/procxx/tdesktop/build/1.0.156-jkqlpgva) (commit https://github.com/procxx/kepka/commit/89b0791abe by @ForNeVeR)

**Comment by ForNeVeR** [comment]
If it works, then I recommend to squash. The intermediate commits are meaningless.

**Comment by crackedmind** [comment]
:x: [Build kepka 1.0.157-ceaxqfnl failed](https://ci.appveyor.com/project/procxx/tdesktop/build/1.0.157-ceaxqfnl) (commit https://github.com/procxx/kepka/commit/2881df8049 by @ForNeVeR)

**Comment by crackedmind** [comment]
:white_check_mark: [Build kepka 1.0.157-uflpddqr completed](https://ci.appveyor.com/project/procxx/tdesktop/build/1.0.157-uflpddqr) (commit https://github.com/procxx/kepka/commit/97b738e32f by @ForNeVeR)

**Pull request merged**
