### PR TITLE
Simplify lambdas, 

### PR DESCRIPTION
**Pull request by Randl**
Backport

### CODE REVIEW

**Comment by crackedmind** [comment]
:white_check_mark: [Build kepka 1.0.134-uhytgggx completed](https://ci.appveyor.com/project/procxx/tdesktop/build/1.0.134-uhytgggx) (commit https://github.com/procxx/kepka/commit/ab523b8325 by @Randl)

**Comment by Randl** [comment]
Possibly part of https://github.com/procxx/kepka/issues/27

**Comment by berkus** [comment]
Resolve conflicts?

**Comment by crackedmind** [comment]
:white_check_mark: [Build kepka 1.0.141-fwyihqvf completed](https://ci.appveyor.com/project/procxx/tdesktop/build/1.0.141-fwyihqvf) (commit https://github.com/procxx/kepka/commit/6cb4980580 by @Randl)

**Comment by crackedmind** [comment]
:white_check_mark: [Build kepka 1.0.142-eiefnpmu completed](https://ci.appveyor.com/project/procxx/tdesktop/build/1.0.142-eiefnpmu) (commit https://github.com/procxx/kepka/commit/9627985072 by @Randl)

**Comment by crackedmind** [comment]
:white_check_mark: [Build kepka 1.0.144-uncpnqnh completed](https://ci.appveyor.com/project/procxx/tdesktop/build/1.0.144-uncpnqnh) (commit https://github.com/procxx/kepka/commit/4b5f73884c by @Randl)

**Pull request merged**
