### PR TITLE
Fix python find

### PR DESCRIPTION
**Pull request by crackedmind**

### CODE REVIEW

**Review by xvitaly — DISMISSED** [review]
LGTM. Fixed build under Fedora 29+.

**Comment by crackedmind** [comment]
:white_check_mark: [Build kepka 1.0.190-ujwdjonw completed](https://ci.appveyor.com/project/procxx/tdesktop/builds/19849235) (commit https://github.com/procxx/kepka/commit/22b19b19ee by @crackedmind)

**Comment by crackedmind** [comment]
:white_check_mark: [Build kepka 1.0.190-ijeaundq completed](https://ci.appveyor.com/project/procxx/tdesktop/builds/19853272) (commit https://github.com/procxx/kepka/commit/fb3b8ce0ce by @crackedmind)

**Review by xvitaly — APPROVED** [review]
LGTM. Fixed build under Fedora 29+.

**Pull request merged**
