### PR TITLE
Fix compile error when building with LibreSSL

### PR DESCRIPTION
**Pull request by kachsheev**
Add preprocessor check of LibreSSL version.

### CODE REVIEW

**Comment by crackedmind** [comment]
:white_check_mark: [Build kepka 1.0.135-bhesnkdo completed](https://ci.appveyor.com/project/procxx/tdesktop/build/1.0.135-bhesnkdo) (commit https://github.com/procxx/kepka/commit/c128290c11 by @kachsheev)

**Review by ForNeVeR — DISMISSED** [review]

**Comment by Randl** [comment]
@kachsheev Please run clang-format on the code

cc @berkus @leha-bot we should some notification for contributors

**Comment by kachsheev** [comment]
@Randl @EvgeniyZh Жень, сделаю это вечером.

**Comment by berkus** [comment]
@Randl just add it to .github/PR_GUIDELINE or however it's called.

**Comment by crackedmind** [comment]
:white_check_mark: [Build kepka 1.0.135-odrrvhoa completed](https://ci.appveyor.com/project/procxx/tdesktop/build/1.0.135-odrrvhoa) (commit https://github.com/procxx/kepka/commit/06cfb382f5 by @kachsheev)

**Review by berkus — APPROVED** [review]

**Pull request merged**
